#!/bin/bash

# Example run
#./data_manage_M2 /scratch/group/astro/data/ROTSE/rotse21/disk2/rotse3 140904 3b
#- update: 6/10/19 - loops all numeric directories and for all telescope type 3a,3b,3c,3d
#-./data_manage_M2 /scratch/group/astro/data/ROTSE/rotse21/disk2/rotse3

copy_files() {
    ndate=$1
    tele=$2
    imgfiles=$indir'/'$ndate'/image/'
    prodfiles=$indir'/'$ndate'/prod/'
    yy=${ndate:0:2}
    mm=${ndate:2:2}
    dd=${ndate:4:2}
    echo $yy $mm $dd
    outdir=$outpath'/rdata/'$tele'/'$yy'/'$mm'/'$dd
    logfile=$outpath'/rdata/'$ndate'_'$tele'_copylog.txt'
    echo Log file is $logfile
    outimg=$outdir'/image/'
    outprod=$outdir'/prod/'
    coaddimg=$outdir'/coadd/image/'
    coaddprod=$outdir'/coadd/prod/'

    if [ ! -d "$outimg" ]; then
        echo $outimg does not exist. Writing the directory
        mkdir -p "$outimg"
    fi
 
    if [ ! -d "$outprod" ]; then
        echo $outprod does not exist. Writing the directory
        mkdir -p "$outprod"
    fi
    #- copy images and prod
    echo copying to image.....
    coadd_im=0
    raw_im=0
    for im in $imgfiles/*${tele}*; do
        if [[ $im = *${tele}*"-0"* ]]; then
            #-echo 'copying' $im to $coaddimg;
            #echo $im '  ----  ' $coaddimg $'\r' >> $logfile
            if [ ! -d "$coaddimg" ]; then
                echo $coaddimg does not exist. Writing the directory;
                mkdir -p "$coaddimg"
            fi
            #- check for duplicates
            imfile=$(echo $im | xargs -n 1 basename)
            if [ -f "$coaddimg/$imfile" ]; then
                echo 'DUPLICATE!!! '$im ' already exists. Not copying.....' $'\r' >> logfile
            else
                cp $im $coaddimg
                echo $im '  ----  ' $coaddimg $'\r' >> $logfile
            if [ $? -eq 0 ]; then
                coadd_im=$((coadd_im + 1))
            fi
        elif [[ $im = *${tele}* ]]; then 
            #- echo 'copying '$im to $outimg;
            #- check for duplicates
            imfile=$(echo $im | xargs -n 1 basename)
            if [ -f "$outimg/$imfile" ]; then
                echo 'DUPLICATE!!! '$im ' already exists. Not copying.....' $'\r' >> logfile
            else
                cp $im $outimg
                echo $im '  ----  ' $outimg $'\r' >> $logfile
            if [ $? -eq 0 ]; then
                raw_im=$((raw_im + 1)) 
            fi
        fi
    done
    echo Total Coadded images copied: $coadd_im
    echo Total raw images copied: $raw_im
    echo copying to prod.....
    coadd_prod=0
    raw_prod=0
    for pp in $prodfiles/*${tele}*; do
        if [[ $pp = *${tele}*"-0"* ]]; then
            #- echo 'copying' $pp to $coaddprod;
            #echo $pp '  ----  ' $coaddprod $'\r' >> $logfile
            if [ ! -d "$coaddprod" ]; then
                echo $coaddprod does not exist. Writing the directory
                mkdir -p "$coaddprod"
            fi
            #- check for duplicates
            prodfile=$(echo $pp | xargs -n 1 basename)
            if [ -f "$coaddprod/$prodfile" ]; then
                echo 'DUPLICATE!!! '$pp ' already exists. Not copying.....' $'\r' >> $logfile
            else
                cp $pp $coaddprod
                echo $pp '  ----  ' $coaddprod $'\r' >> $logfile
            if [ $? -eq 0 ]; then
                coadd_prod=$((coadd_prod + 1))
            fi
        elif [[ $pp = *${tele}* ]]; then
            #- echo 'copying '$pp to $outprod;

            #- check for duplicates
            prodfile=$(echo $pp | xargs -n 1 basename)
            if [ -f "$outprod/$prodfile" ]; then
                echo 'DUPLICATE!!! '$pp ' already exists. Not copying.....' $'\r' >> $logfile
            else
                cp $pp $outprod
                echo $pp '  ----  ' $outprod $'\r' >> $logfile

            if [ $? -eq 0 ]; then
                raw_prod=$((raw_prod + 1))
            fi
        fi
    done
    echo Total Coadded prod files copied: $coadd_prod
    echo Total raw prod files copied: $raw_prod
}

indir="$1"
cd $indir
ndates=$(ls -d */ | sed 's#/##' | grep [0-9])
#ndates=$(ls -d +([0-9])) # -d #-d +([0-9]))"
#ndates=$(ls -d | grep [0-9])
echo dates: $ndates
for ndate in $ndates; do
    #outpath='/users/gdhungana/test_m2/m2manage'
    outpath='/scratch/group/astro/data/ROTSE'
    for tele in '3a' '3b' '3c' '3d'; do
        echo copying ROTSE files of $ndate telescope $tele
        copy_files $ndate $tele
    done
done

